#!/bin/bash
dir="$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)"
cd $dir
dotnet Jenny/Jenny.Generator.Cli.dll auto-import -s
dotnet Jenny/Jenny.Generator.Cli.dll doctor
read -n 1 -srp "Press any key to continue"
